### ISSUE TITLE
roadmap for experimental

### ISSUE THREAD

**Issue by brrzap** [brrzap/tootstream#3]
these are not in any sort of priority order, but here's things i'm considering:

- [ ] toot drafts.  spawn external editor for toot input?
- [ ] attach (read in) text files. if too long, auto-post to a pastebin service? auto-split and chain-post?
- [ ] pager for long lists.
- [ ] language tools: auto-identify, user preferences, output filtering ([upstream#62](https://github.com/magicalraccoon/tootstream/issues/62))
- [ ] language tools: `translate` command ([upstream#72](https://github.com/magicalraccoon/tootstream/issues/72))
- [ ] saved-settings scaffolding to support colorschemes, language prefs, etc
- [ ] lists.  yeah like birbsite.  would have to be client-side.
- [ ] bookmarks / saved searches.
- [ ] data caching?
- [ ] account settings -- `display_name`, note, avatar/background image upload -- are the only changes we can make through API?
- [ ] (n)curses. dare we even think it?
- [ ] testing.

already implemented here:

- [x] "raw output" mode -- every detail about a toot/user we can put on the screen (`raw` cmd)
- [x] media. [upstream#24](https://github.com/magicalraccoon/tootstream/issues/24), [experimental#2](#2) (`toot`, `reply` cmd opts)
- [x] toot/reply sensitivity, CW options. (`toot`, `reply` cmd opts)
- [x] bash-style multiline commands (`help :multiline`)
- [x] specific-user timeline. (`timeline` cmd)
- [x] favorites (`faves` cmd)
- [x] relationship analysis (who's following you that you also/don't follow/block/whatever) (`follow show` cmd)
- [x] streaming. notifications.  (`stream`, `listen` cmds)
- [x] thread/history command [upstream#53](https://github.com/magicalraccoon/tootstream/issues/53)
- [x] profile hotswapping [upstream#51](https://github.com/magicalraccoon/tootstream/issues/51) (`profile` cmds)
- [x] server info (`profile info` cmd)

in upstream:

- [x] profiles (cli opt) [upstream#94](https://github.com/magicalraccoon/tootstream/issues/94)
- [x] follow/mute/block list management [upstream#70,](https://github.com/magicalraccoon/tootstream/issues/70)[#71](https://github.com/magicalraccoon/tootstream/issues/71)
- [x] user/hashtag search [upstream#57](https://github.com/magicalraccoon/tootstream/issues/57)
- [x] local timeline [upstream#56](https://github.com/magicalraccoon/tootstream/issues/56)
